8 instead of 9, bah to java.lang.NoClassDefFoundError: org/tanesha/replacer/FormatterException
git-svn-id: http://svn.code.sf.net/p/drftpd/svn/trunk@600 c83153ee-f3e8-0310-b165-dc3a72e09794